# Generated by Django 3.2.8 on 2021-10-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trumbler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_num', models.IntegerField(blank=True, null=True)),
                ('status_text', models.TextField(blank=True, null=True)),
                ('status_name', models.TextField(blank=True, null=True)),
                ('status_created_at', models.TextField(blank=True, null=True)),
                ('status_favourate_Count', models.TextField(blank=True, null=True)),
                ('status_lang', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_num', models.IntegerField(blank=True, null=True)),
                ('status_text', models.TextField(blank=True, null=True)),
                ('status_name', models.TextField(blank=True, null=True)),
                ('status_created_at', models.TextField(blank=True, null=True)),
                ('status_favourate_Count', models.TextField(blank=True, null=True)),
                ('status_lang', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
